<?php


namespace AppTest;

use App\Service\Container;
use PHPUnit\Framework\TestCase;


class ExceptionTest extends TestCase
{
    private Container $container;

    protected function setUp(): void
    {
        $this->container = new Container();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testExceptionWhenClassInvalid(): void
    {
        $id = 'some invalid class';

        $this->expectException(\Exception::class);
        $this->expectExceptionMessage('Class ID invalid');
        $this->container->get($id);
    }
}