<?php


namespace AppTest\Controller;

use App\Service\View;
use App\Service\Container;
use App\Controller\ProductDetails;
use App\Model\ProductRepository;
use PHPUnit\Framework\TestCase;


class ProductDetailsTest extends TestCase
{
    private View $view;
    private ProductDetails $productDetails;
    private ProductRepository $productRepository;

    protected function setUp(): void
    {
        $container = new Container();
        $this->view = new View();
        $container->set(View::class, $this->view);
        $this->productRepository = new ProductRepository();
        $this->productDetails = new ProductDetails($container, $this->productRepository);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testActionWhereProductExists(): void
    {
        $id = $_GET['pid'] = 1;

        $this->productDetails->action();

        self::assertSame('productDetails.tpl', $this->view->getTemplate());

        $params = $this->view->getParams();
        self::assertCount(3, $params);
        self::assertSame('Product Details', $params['headline']);
        self::assertSame('All infos about your product:', $params['info']);
        self::assertSame($this->productRepository->get($id), $params['singleProduct']);
    }

    public function testActionWhereProductNotExists(): void
    {
        $_GET['pid'] = 9999;
        $this->productDetails->action();

        self::assertSame('404.tpl', $this->view->getTemplate());

        $params = $this->view->getParams();
        self::assertCount(2, $params);
        self::assertSame('ERROR 404', $params['headline']);
        self::assertSame('Product not found', $params['info']);
    }

    public function testActionWhereProductIdNotExists(): void
    {
        $this->productDetails->action();

        self::assertSame('404.tpl', $this->view->getTemplate());

        $params = $this->view->getParams();
        self::assertCount(2, $params);
        self::assertSame('ERROR 404', $params['headline']);
        self::assertSame('Product not found', $params['info']);

    }

    protected function tearDown(): void
    {
        $_GET = [];

        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}


