<?php


namespace AppTest\Controller;

use App\Service\View;
use App\Service\Container;
use App\Controller\About;
use PHPUnit\Framework\TestCase;


class AboutTest extends TestCase
{
    private View $view;
    private About $about;

    protected function setUp(): void
    {
        $container = new Container();
        $this->view = new View();
        $container->set(View::class, $this->view);
        $this->about = new About($container);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testWhereAboutExists(): void
    {
        $this->about->action();

        self::assertSame('about.tpl', $this->view->getTemplate());

        $params = $this->view->getParams();
        self::assertCount(2, $params);
        self::assertSame('About', $params['headline']);
        self::assertSame('We are Nexus', $params['info']);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}