<?php


namespace AppTest\Controller;

use App\Service\View;
use App\Controller\Error;
use App\Service\Container;
use PHPUnit\Framework\TestCase;


class ErrorTest extends TestCase
{
    private View $view;
    private Error $error;

    protected function setUp(): void
    {
        $container = new Container();
        $this->view = new View();
        $container->set(View::class, $this->view);
        $this->error = new Error($container);


        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testWhereErrorExists(): void
    {
        $this->error->action();

        self::assertSame('404.tpl', $this->view->getTemplate());

        $params = $this->view->getParams();
        self::assertCount(2, $params);
        self::assertSame('ERROR 404', $params['headline']);
        self::assertSame('Page not found', $params['info']);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}