<?php


namespace AppTest\Controller;

use App\Service\Container;
use App\Service\View;
use App\Controller\Home;
use PHPUnit\Framework\TestCase;


class HomeTest extends TestCase
{
    private View $view;
    private Home $home;

    protected function setUp(): void
    {
        $container = new Container();
        $this->view = new View();
        $container->set(View::class, $this->view);
        $this->home = new Home($container);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testWhereHomeExists():void
    {
        $this->home->action();

        self::assertSame('layout.tpl', $this->view->getTemplate());

        $params = $this->view->getParams();
        self::assertCount(2, $params);
        self::assertSame('Home', $params['headline']);
        self::assertSame('Welcome', $params['info']);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}